server:
  port: 8081 #服务端口

###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如商品服务)
spring:
    application:
        name: app-item
###服务注册到zookeeper注册中心的地址
    cloud:
        zookeeper:
          connect-string: 127.0.0.1:2181
